# Generated by Django 3.2.23 on 2024-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='spf',
            field=models.TextField(verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='summary',
            field=models.TextField(verbose_name='summary'),
        ),
    ]
